---
- name: Create User with RSA key and Enable SSH
  hosts: "{{ nodes }}"
  become: true
  tasks:
    - name : Create user with secret key
      user:
          name: "{{ item }}"
          shell: /bin/bash 
          ssh_key_file: "~/.ssh/{{ item }}@tc"
          ssh_key_type: rsa
      loop: "{{ username }}"

    - name: Add the pub key to the authorized list
      authorized_key:
        user: "{{ item }}"
        key: "{{ lookup('file', '~/.ssh/{{ item }}@tc.pub') }}"
      loop: "{{ username }}"