version: '3.8'

services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    pull_policy: always
    container_name: zigbee2mqtt
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=Europe/Berlin
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro