version: '3.8'
networks:
  tc_infrastructure:
    driver: bridge

services:
  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    command: --config.file=/config/blackbox.yml
    networks:
      - tc_infrastructure
    restart: always
    volumes:
      - ./prometheus/blackbox.yml:/config/blackbox.yml

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    networks:
      - tc_infrastructure
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=web
      - traefik.http.routers.grafana.rule=Host(`grafana.termite.cloud`)
      - traefik.http.services.gragana.loadbalancer.server.port=3000
    restart: always
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/dashboards/templates:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
  
  mosquitto: 
    image: eclipse-mosquitto
    container_name: mosquitto
    command: "mosquitto -c /mosquitto-no-auth.conf"
    networks:
      - tc_infrastructure
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mosquitto.entrypoints=mqtt
      - traefik.tcp.routers.mosquitto.rule=HostSNI(`*`)
      - traefik.tcp.services.mosquitto.loadbalancer.server.port=1883
    restart: always
    volumes:
      - mosquitto_data:/mosquitto
      - ./mosquitto:/etc/mosquitto
  
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - tc_infrastructure
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.routers.portainer.rule=Host(`portainer.termite.cloud`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - tc_infrastructure
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.entrypoints=web
      - traefik.http.routers.prometheus.rule=Host(`prometheus.termite.cloud`)
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  traefik:
    image: traefik
    container_name: traefik
    networks:
      - tc_infrastructure
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.rule=Host(`traefik.termite.cloud`)
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.tls.certresolver=letsencrypt
      # global redirect to https
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https
      # middleware redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    ports:
      - 80:80
      - 443:443
      - 1883:1883
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml

volumes:
  grafana_data:
  mosquitto_data:
  portainer_data: