version: '3.8'
networks:
  infrastructure_tc_infrastructure:
    external: true

services:
  termite_cloud:
      image: ghcr.io/pedroars99/termite-cloud:latest
      pull_policy: always
      container_name: termite_cloud
      networks:
        - infrastructure_tc_infrastructure
      env_file:
        - .env
      labels:
        - traefik.enable=true
        - traefik.http.routers.termite_cloud.entrypoints=websecure
        - traefik.http.routers.termite_cloud.rule=Host(`termite.cloud`)
        - traefik.http.routers.termite_cloud.tls=true
        - traefik.http.routers.termite_cloud.tls.certresolver=letsencrypt
        - traefik.http.services.termite_cloud.loadbalancer.server.port=3000