version: '3.8'
services:

  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox_exporter
    command: --config.file=/config/blackbox.yml
    restart: always
    volumes:
      - ./prometheus/blackbox.yml:/config/blackbox.yml

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.entrypoints=web
      - traefik.http.routers.grafana.rule=Host(`grafana.termite.cloud`)
      - traefik.http.services.gragana.loadbalancer.server.port=3000
    restart: always
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana
  
  mosquitto: 
    image: eclipse-mosquitto
    container_name: mosquitto
    command: "mosquitto -c /mosquitto-no-auth.conf"
    labels:
      - traefik.enable=true
      - traefik.tcp.routers.mosquitto.entrypoints=mqtt
      - traefik.tcp.routers.mosquitto.rule=HostSNI(`*`)
      - traefik.tcp.services.mosquitto.loadbalancer.server.port=1883
    restart: always
    volumes:
      - mosquitto_data:/mosquitto
      - ./mosquitto:/etc/mosquitto
  
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.routers.portainer.rule=Host(`portainer.termite.cloud`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    labels:
      - traefik.enable=true
      - traefik.http.routers.prometheus.entrypoints=web
      - traefik.http.routers.prometheus.rule=Host(`prometheus.termite.cloud`)
      - traefik.http.services.prometheus.loadbalancer.server.port=9090
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  termite_cloud:
    image: ghcr.io/pedroars99/termite-cloud:latest
    pull_policy: always
    container_name: termite_cloud
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.termite_cloud.entrypoints=web
      - traefik.http.routers.termite_cloud.rule=Host(`termite.cloud`)
      - traefik.http.services.termite_cloud.loadbalancer.server.port=3000
    restart: always

  traefik:
    image: traefik
    container_name: traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.entrypoints=web
      - traefik.http.routers.dashboard.rule=Host(`traefik.termite.cloud`)
      - traefik.http.routers.dashboard.service=api@internal
    ports:
      - 80:80
      - 1883:1883
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
volumes:
  grafana_data:
  mosquitto_data:
  portainer_data: