apiVersion: 1
datasources:
  - name: CloudWatch
    type: cloudwatch
    jsonData:
      authType: keys
      defaultRegion: eu-central-1
    secureJsonData:
      accessKey: $GF_CLOUDWATCH_ACCESS_KEY
      secretKey: $GF_CLOUDWATCH_SECRET_KEY