---
- name: Deploy the Termite Cloud App
  hosts: "{{ nodes }}"
  tasks:
    - name: Checkout
      git:
        repo: "{{ repo }}"
        dest: "{{ src }}"

    - name: Tear down
      docker_compose:
        project_src: "{{ src }}/cloud/docker"
        remove_images: all
        state: absent
    
    - name: Launch
      docker_compose:
        project_src: "{{ src }}/cloud/docker"
        pull: yes
        recreate: always
        state: present
      environment:
        S3_ACCESS_KEY: "{{ S3_ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ S3_SECRET_KEY }}"

