---
- name: Deploy the Termite Cloud App
  hosts: "{{ nodes }}"
  tasks:
    - name: Checkout
      git:
        repo: "{{ repo }}"
        dest: "{{ src }}"

    - name: Tear down
      docker_compose:
        project_src: "{{ src }}/cloud/docker/{{ profile }}"
        remove_images: all
        state: absent
    
    - name: Launch
      docker_compose:
        project_src: "{{ src }}/cloud/docker/{{ profile }}"
        pull: yes
        recreate: always
        state: present

