name: Deploy Terraform Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - cloud/terraform/*

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

jobs:
  deploy_terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cloud/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Format
        run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Apply
        run: terraform apply -auto-approve
  
  configure_instance:
    runs-on: ubuntu-latest
    needs: deploy_terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Install Docker playbook
        uses: dawidd6/action-ansible-playbook@v2.6.1
        with:
          playbook: install_docker.yaml
          directory: ./cloud/ansible/playbooks/install_docker
          key: ${{ secrets.ANSIBLE_SSH_KEY }}
          options: |
              --inventory ../../hosts
              --extra-vars "@variables.yaml"
